// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHkl05OjZyAFBRdctEeDFNL_VmjfZN5R0',
    appId: '1:98977359608:web:ba0102bc600e4590f6bd0d',
    messagingSenderId: '98977359608',
    projectId: 'jevlis-ka-part2',
    authDomain: 'jevlis-ka-part2.firebaseapp.com',
    storageBucket: 'jevlis-ka-part2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxuJnvMhzwDWR9QfCTpnMMbjwaJJ0-jLw',
    appId: '1:98977359608:android:8f9e64a5e3101f66f6bd0d',
    messagingSenderId: '98977359608',
    projectId: 'jevlis-ka-part2',
    storageBucket: 'jevlis-ka-part2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRp-MuTs_ZErmDCFn8E82ru7frvf3DrGA',
    appId: '1:98977359608:ios:657ae3a325b529acf6bd0d',
    messagingSenderId: '98977359608',
    projectId: 'jevlis-ka-part2',
    storageBucket: 'jevlis-ka-part2.appspot.com',
    iosClientId: '98977359608-n09eoupoilk3khad665e03sesea0edsd.apps.googleusercontent.com',
    iosBundleId: 'com.jevliska.jevlisKa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRp-MuTs_ZErmDCFn8E82ru7frvf3DrGA',
    appId: '1:98977359608:ios:657ae3a325b529acf6bd0d',
    messagingSenderId: '98977359608',
    projectId: 'jevlis-ka-part2',
    storageBucket: 'jevlis-ka-part2.appspot.com',
    iosClientId: '98977359608-n09eoupoilk3khad665e03sesea0edsd.apps.googleusercontent.com',
    iosBundleId: 'com.jevliska.jevlisKa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHkl05OjZyAFBRdctEeDFNL_VmjfZN5R0',
    appId: '1:98977359608:web:ba0102bc600e4590f6bd0d',
    messagingSenderId: '98977359608',
    projectId: 'jevlis-ka-part2',
    authDomain: 'jevlis-ka-part2.firebaseapp.com',
    storageBucket: 'jevlis-ka-part2.appspot.com',
  );

}